# -*- coding: utf-8 -*-
"""hopfield.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VOb87cJCdPpyvz-jIoP-lxH8q7WE89q8
"""

import numpy as np
v1 = np.array([1, -1, 1, -1])
v2 = np.array([-1, 1, -1, 1])
v3 = np.array([1, 1, -1, -1])
v4 = np.array([-1, -1, 1, 1])
w = np.zeros((4, 4))
w

for v in [v1, v2, v3, v4]:
    w += np.outer(v, v)
print(w)

def sign(x):
    return 1 if x >= 0 else -1
def hopfield_network(x, w, iterations):
    for i in range(iterations):
        x = np.array([sign(np.dot(w[i], x)) 
        for i in range(len(x))])
    return x
x = np.array([1, -1, 1, -1])
print(hopfield_network(x, w, 5))

